Repository woowa-techcamp-2021/deal-19, pull requests merged in 2021-07, with the labels that each got.

#39 (#3) Update: eslint prettier extension 삭제 및 indent 규칙 추가
  .eslintrc.cjs
  package-lock.json
Labels: setting

#40 (#2) Update: webpack dev 서버 적용
  app.js
  devServerMiddleware.js
  package-lock.json
  package.json
  public/pages/chatDetail/index.html
  public/pages/chatDetail/index.js
  public/pages/chatDetail/style.scss
  public/pages/chatList/index.html
  public/pages/chatList/index.js
  public/pages/chatList/style.scss
  public/pages/editor/index.html
  public/pages/editor/index.js
  public/pages/editor/style.scss
  public/pages/location/index.html
  public/pages/location/index.js
  public/pages/location/style.scss
  public/pages/main/index.html
  public/pages/main/index.js
  public/pages/main/style.scss
  public/pages/productDetail/index.html
  public/pages/productDetail/index.js
  public/stylesheets/style.sass
  routes/index.js
  webpack.config.js
Labels: setting

#41 (#4) Update: 백엔드 라우팅 디렉토리 구조 수정
  routes/chatDetail/index.js
  routes/chatList/index.js
  routes/editor/index.js
  routes/index.js
  routes/location/index.js
  routes/main/index.js
  routes/productDetail/index.js
Labels: setting

#44 (#4) Init: 글로벌 스타일 적용
  public/assets/account.svg
  public/assets/add.svg
  public/assets/arrow_back.svg
  public/assets/arrow_forward.svg
  public/assets/cancel.svg
  public/assets/category.svg
  public/assets/chat_bubble_mini.svg
  public/assets/done.svg
  public/assets/exit.svg
  public/assets/expand_more.svg
  public/assets/favorite.svg
  public/assets/favorite_border.svg
  public/assets/favorite_border_mini.svg
  public/assets/image.svg
  public/assets/location.svg
  public/assets/menu.svg
  public/assets/more_vert.svg
  public/assets/send.svg
  public/configs/constants.js
  public/configs/globalStyle.scss
  public/configs/preset.scss
  webpack.config.js
Labels: FE, setting

#45 (#43) Feature: 공통 컴포넌트 스타일링
  public/configs/globalStyle.scss
Labels: FE, component

#46 (#21) Feature: 모달 컴포넌트 작성
  public/components/modal.js
  public/components/modal.scss
  public/configs/globalStyle.scss
  public/configs/preset.scss
  webpack.config.js
Labels: FE, component

#47 Init: 아이콘 폰트 적용
  .eslintrc.cjs
  package-lock.json
  package.json
  public/assets/account.svg
  public/assets/add.svg
  public/assets/arrow_back.svg
  public/assets/arrow_forward.svg
  public/assets/cancel.svg
  public/assets/category.svg
  public/assets/chat_bubble_mini.svg
  public/assets/done.svg
  public/assets/exit.svg
  public/assets/expand_more.svg
  public/assets/favorite.svg
  public/assets/favorite_border.svg
  public/assets/favorite_border_mini.svg
  public/assets/fonts/woowa-market-icons.woff
  public/assets/fonts/woowa-market-icons.woff2
  public/assets/image.svg
  public/assets/location.svg
  public/assets/menu.svg
  public/assets/more_vert.svg
  public/assets/send.svg
  public/assets/woowa-market-icons.css
  webpack.config.js
Labels: FE, setting

#48 (#20) Style: 물품 목록 리스트 및 아이템 컴포넌트 마크업
  public/components/list.js
  public/components/list.scss
  public/pages/main/index.js
Labels: FE, component, markup

#49 (#22) Style: header 컴포넌트 markup
  public/components/header.js
  public/components/header.scss
Labels: FE, markup

#50 (#21) Style: 메인화면 마크업
  package.json
  public/configs/mock.data.js
  public/pages/main/index.js
Labels: FE, markup

#51 (#24) Style: 메인페이지 fab 추가
  package-lock.json
  public/configs/globalStyle.scss
  public/pages/main/fab/index.js
  public/pages/main/fab/style.scss
  public/pages/main/index.js
  public/pages/main/style.scss
Labels: FE, markup

#53 (#22) Feat : Header 컴포넌트에서 각종 아이콘 클릭시 함수 호출 로직 구현
  public/components/header.js
  public/components/header.scss
Labels: FE, component

#52 (#23) Style: 드롭다운 추가
  public/components/dropdown.js
  public/components/dropdown.scss
  public/core/Component.js
Labels: FE, component, markup

#54 (#24) Style: 메인 페이지 마크업 (카테고리 view Tabbar)
  public/configs/constants.js
  public/pages/main/category/category.js
  public/pages/main/category/index.js
  public/pages/main/category/style.scss
  public/pages/main/tabBar/index.js
  public/pages/main/tabBar/style.scss
Labels: FE, markup

#58 (#22) Header 컴포넌트 기능 추가구현
  . prettierrc
  .vscode/settings.json
  public/components/header.js
Labels: FE, component

#55 (#24) Style: 메인 페이지 마크업
  public/configs/mock.data.js
  public/pages/main/auth/login.js
  public/pages/main/auth/signup.js
  public/pages/main/login/index.js
  public/pages/main/login/style.scss
  public/pages/main/menu/index.js
  public/pages/main/menu/menu.js
  public/pages/main/menu/style.scss
  public/pages/main/myPage/index.js
  public/pages/main/myPage/myPage.js
  public/pages/main/myPage/style.scss
  public/pages/main/register/index.js
  public/pages/main/register/style.scss
  public/pages/main/tabBar/index.js
Labels: FE, markup

#57 (#30) Style: 상품 상세 페이지 마크업
  public/configs/constants.js
  public/configs/mock.data.js
  public/pages/productDetail/carousel/index.js
  public/pages/productDetail/carousel/style.scss
  public/pages/productDetail/footer/index.js
  public/pages/productDetail/index.js
  public/pages/productDetail/style.scss
  public/utils/parseCategoryType.js
  public/utils/parsePrice.js
  public/utils/parseProductStatus.js
  public/utils/timeFromNow.js
Labels: FE, component, markup

#61 (#7) Init: mysql 설치 및 설정
  .gitignore
  app.js
  env.js
  mock.env
  model/db.js
  model/init.sql
  model/query/auth.js
  package-lock.json
  package.json
  public/configs/mock.data.js
Labels: BE, setting

#65 (#62) Update: 폴더 구조 변경
  api/chat/delete.js
  api/chat/get.js
  api/chat/index.js
  api/chat/post.js
  api/index.js
  app.js
Labels: API, BE, setting

#66 (#7) Init sql 스크립트 수정
  model/init.sql
Labels: BE, setting

#67 (#64) Feature: GET /items 1차 코드
  api/items/get.js
  package-lock.json
  package.json
  utils/errorGenerator.js
  utils/validateAuth.js
Labels: API, BE

#68 (#31) 슬라이더의 헤더 생성 책임 제거, 위임
  public/components/slider.js
  public/pages/main/style.scss
Labels: FE, component

#73 (#72) Auth 관련 API 작성
  api/auth/signin/index.js
  api/auth/signup/index.js
  model/db.js
  model/init.sql
  utils/jwt.js
  utils/validateAuth.js
Labels: API, BE

#75 (#15) 글쓰기 화면 마크업 복구 / 글쓰기 요청
  public/components/header.js
  public/pages/editor/editorForm/index.js
  public/pages/editor/editorForm/style.scss
  public/pages/editor/index.js
  public/pages/main/index.js
Labels: FE, markup

#77 (#72) API 에러발생시 응답 메세지 추가
  api/auth/signin/index.js
  api/auth/signup/index.js
Labels: API, BE

#76 (#12) 메인 페이지 로그인 화면 기능 추가
  public/components/slider.js
  public/configs/endpoints.js
  public/pages/main/index.js
  public/pages/main/login/index.js
  public/pages/main/login/style.scss
  public/utils/fetchWrapper.js
Labels: FE

#78 (#12) 로그인 페이지 회원가입 이동 버그 해결
  public/components/slider.js
  public/pages/main/index.js
  public/pages/main/login/index.js
Labels: FE, bug

#80 Fix: prod 모드가 제대로 열리지 않는 버그 수정
  api/app.js
  api/package-lock.json
  api/package.json
  api/utils/env.js
  client/app.js
  client/public/assets/favicon.ico
  client/public/assets/favicon.png
  client/webpack.common.js
Labels: FE, setting

#82 (#12) Feature: 내 계정화면 기능 추가
  client/mock.env
  client/public/components/slider.js
  client/public/components/slider.scss
  client/public/configs/endpoints.js
  client/public/pages/main/login/index.js
  client/public/pages/main/myPage/index.js
  client/public/pages/main/register/index.js
  client/public/pages/main/register/style.scss
  client/public/pages/main/style.scss
Labels: FE

#83 client, api 폴더에 eslint 적용
  api/.eslintrc.cjs
  api/package-lock.json
  api/package.json
  client/.eslintrc.cjs
Labels: setting

#84 Update: DB 모델 수정 및 jwt 해독 함수 추가
  api/model/init.sql
  api/utils/jwt.js
Labels: BE

#85 (#15) 글쓰기 화면 글쓰기 요청
  api/.eslintrc.cjs
  client/public/configs/endpoints.js
  client/public/configs/mock.data.js
  client/public/pages/editor/editorForm/index.js
  client/public/pages/editor/index.js
  client/public/pages/main/login/index.js
Labels: FE

#87 (#64) GET /items API
  api/routes/items/get.js
Labels: API, BE

#88 (#32) fix: 세미 프레임워크 didMount 무한 루프 문제 해결.
  client/public/core/Component.js
Labels: FE, setting

#95 (#22) header 미세 조정
  client/public/components/header.js
  client/public/components/header.scss
  client/public/configs/globalStyle.scss
  client/public/pages/editor/editorForm/index.js
  client/public/pages/editor/index.js
  client/public/pages/location/index.js
  client/public/pages/location/style.scss
Labels: FE, markup

#94 (#29) 내 동네 설정하기 마크업
  client/public/pages/location/index.js
  client/public/pages/location/style.scss
Labels: FE, markup

#93 (#89) API HEAD /auth
  api/routes/auth/head.js
  api/routes/auth/towns/get.js
Labels: API, BE

#91 (#90) API GET /auth/towns 추가
  api/routes/auth/towns/get.js
  api/routes/auth/towns/index.js
Labels: API, BE

#97 메인페이지 기능 추가
  api/routes/auth/index.js
  api/routes/items/get.js
  client/public/components/dropdown.scss
  client/public/components/list.js
  client/public/components/list.scss
  client/public/configs/endpoints.js
  client/public/pages/main/category/index.js
  client/public/pages/main/fab/index.js
  client/public/pages/main/fab/style.scss
  client/public/pages/main/index.js
  client/public/pages/main/myPage/index.js
  client/public/pages/main/style.scss
Labels: API, BE, FE

#98 (#21) prompt 모달의 인풋 내용을 action에 전달하도록 수정
  client/public/components/modal.js
  client/public/configs/endpoints.js
  client/public/pages/location/index.js
  client/public/pages/location/style.scss
Labels: FE, component

#104 (#16) 제품 상세 페이지 기능
  api/routes/items/get.js
  client/public/pages/productDetail/index.js
  client/routes/productDetail/index.js
Labels: API, FE

#109 (#108) API 리팩토링
  api/app.js
  api/configs/constant.js
  api/middlewares/validateAuth.js
  api/model/db.js
  api/model/query.js
  api/model/query/auth.js
  api/routes/auth/head.js
  api/routes/auth/signin/index.js
  api/routes/auth/signup/index.js
  api/routes/auth/towns/delete.js
  api/routes/auth/towns/get.js
  api/routes/auth/towns/post.js
  api/routes/index.js
  api/routes/items/get.js
  api/routes/items/post.js
  api/routes/products/delete.js
  api/routes/products/get.js
  api/routes/products/index.js
  api/routes/products/like/index.js
  api/routes/products/post.js
  api/routes/products/put.js
  api/utils/errorGenerator.js
  api/utils/jwt.js
Labels: API, BE
